### ISSUE TITLE
License questions

### ISSUE THREAD

**Issue by kenchris** [NordicPlayground/webapp-nordic-thingy#3]
According to (https://devzone.nordicsemi.com/blogs/1122/introducing-nordics-new-software-licensing-schemes/) all Nordic mobile application examples (with the exception of nRF Connect) use this type of license agreement. So shouldn't this follow this license instead?

For instance, the below doesn't really apply to web apps which are not distributed as binaries:

> 5. Any software provided in binary form under this license must not be reverse
   engineered, decompiled, modified and/or disassembled.

**Comment by ketile** [comment]
I agree that your quoted part does not apply to the web app. However, the decision was made to have the same license for all the Thingy apps for simplicity. You can verify that the [Android](https://github.com/NordicSemiconductor/Android-Nordic-Thingy/blob/master/LICENSE) and [iOS](https://github.com/NordicSemiconductor/ios-nordic-thingy/blob/master/LICENSE) Thingy apps have the same license.

If you think the license is to restrictive or would like changes please make a comment on the blog post on DevZone.

**Comment by kenchris** [comment]
Personally, I see nothing special or proprietary in the source code, so I would go for a non restrictive but common license.

In order to avoid conflict of interest, big companies like to verify what their employees are working on - even in spare time. So derived licenses or special licenses sometimes have to go through legal review, so this can easily mean that some will retain from contributing.

Common licenses are normally already approved.

I would assume this applies to the native apps as well
