### ISSUE TITLE
service-worker.js 404 Not Found on live version

### ISSUE THREAD

**Issue by DurandA** [NordicPlayground/webapp-nordic-thingy#5]
On the web app at [https://developer.nordicsemi.com/thingy/52](https://developer.nordicsemi.com/thingy/52/) there is a call to https://developer.nordicsemi.com/service-worker.js which return a 404 Not Found.

**Comment by ketile** [comment]
Thanks for reporting. We are releasing a new version of the Thingy:52 web app built with React insted of Polymer and will not fix this issue.
